apiVersion: v1
kind: Service
metadata:
  name: {{ include "ira.componentName" (dict "ctx" $ "component" "api") }}
  labels:
    {{- include "ira.labels" (dict "ctx" $ "component" "api") | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "ira.selectorLabels" (dict "ctx" $ "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
